services:
  - type: web
    name: learnedge-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false # You will need to provide this environment variable manually in the Render Dashboard
